name: Deploy

on:
  push:
   branches:
    - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploying
        run: echo "Deploying to dev branch"
